"""Provide datas to graphinder."""


def gql_endpoints_characterizer() -> list[str]:
    """return list of most common GQL endpoints."""

    return [
        'graphql',
        'appsync',
        'altair',
        'explorer',
        'graphiql',
        'playground',
        'subscriptions',
        'graph',
        'graphiql.css',
        'graphiql/finland',
        'graphiql.js',
        'graphiql.min.css',
        'graphiql.min.js',
        'graphiql.php',
        'graphql/console',
        'graphql-explorer',
        'graphql.php',
        'graphql/schema.json',
        'graphql/schema.xml',
        'graphql/schema.yaml',
        'api/graphql',
        'v1/altair',
        'v1/explorer',
        'v1/graphiql',
        'v1/graphiql.css',
        'v1/graphiql/finland',
        'v1/graphiql.js',
        'v1/graphiql.min.css',
        'v1/graphiql.min.js',
        'v1/graphiql.php',
        'v1/graphql',
        'v1/graphql/console',
        'v1/graphql-explorer',
        'v1/graphql.php',
        'v1/graphql/schema.json',
        'v1/graphql/schema.xml',
        'v1/graphql/schema.yaml',
        'v1/playground',
        'v1/subscriptions',
        'v1/api/graphql',
        'v1/graph',
        'v2/altair',
        'v2/explorer',
        'v2/graphiql',
        'v2/graphiql.css',
        'v2/graphiql/finland',
        'v2/graphiql.js',
        'v2/graphiql.min.css',
        'v2/graphiql.min.js',
        'v2/graphiql.php',
        'v2/graphql',
        'v2/graphql/console',
        'v2/graphql-explorer',
        'v2/graphql.php',
        'v2/graphql/schema.json',
        'v2/graphql/schema.xml',
        'v2/graphql/schema.yaml',
        'v2/playground',
        'v2/subscriptions',
        'v2/api/graphql',
        'v2/graph',
    ]
