name: CI
on: [push, pull_request]

env:
  MODULE_NAME: graphinder
  MIN_TEST_COV: 80

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install poetry
      - name: Setup poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run lint
        if: always()
        run: |
          source .venv/bin/activate
          isort -m 9 --line-length 159 $MODULE_NAME tests --check-only
          pylint --load-plugins pylint_quotes $MODULE_NAME tests
          docformatter --wrap-summaries 160 --wrap-descriptions 160 -cr $MODULE_NAME tests
          yapf -rd $MODULE_NAME tests
          mypy -V
          mypy $MODULE_NAME tests
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --cov=$MODULE_NAME --cov-fail-under=$MIN_TEST_COV tests/unit
